"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { apiFetch, closeJd, hasRole, publishJd } from "@/lib/api";
import type { AdminDashboard, JD } from "@/types/api";

type ManagedJD = JD & { status: string; is_published: boolean; location?: string | null; employment_type?: string | null };

export default function AdminJdsPage() {
  const [jds, setJds] = useState<ManagedJD[]>([]); const [admin, setAdmin] = useState<AdminDashboard | null>(null); const [clientName, setClientName] = useState(""); const [rawText, setRawText] = useState(""); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { const [items, dashboard] = await Promise.all([apiFetch<ManagedJD[]>("/jds/"), apiFetch<AdminDashboard>("/dashboard/admin")]); setJds(items); setAdmin(dashboard); }
  useEffect(() => { if (!hasRole("admin", "leadership")) { setError("Admin or leadership access is required."); return; } load().catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load JD workspace.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(null); try { await apiFetch("/jds/", { method: "POST", body: JSON.stringify({ client_name: clientName, raw_text: rawText }) }); setClientName(""); setRawText(""); setMessage("JD analysed and saved as a draft."); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to create JD."); } }
  async function changeStatus(jd: ManagedJD) { try { if (jd.is_published) await closeJd(jd.id); else await publishJd(jd.id); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to update JD status."); } }
  if (error && !admin) return <main className="text-[#F0F4FF]"><p className="text-[#EF4444]">{error}</p><Link href="/login" className="mt-4 inline-block text-[#00B5E2]">Sign in</Link></main>;
  if (!admin) return <main className="text-[#8899BB]">Loading JD workspace...</main>;
  return <div><header className="mb-8 flex items-end justify-between"><div><p className="hcl-label">Admin portal</p><h1 className="mt-2 text-2xl font-semibold">Job descriptions</h1><p className="mt-2 text-[#8899BB]">Create, analyse, publish, and close real opportunities.</p></div><Link href="/admin/applications" className="hcl-button-secondary">Applications</Link></header><section className="mb-8 grid gap-4 md:grid-cols-3"><div className="hcl-card p-5"><p className="hcl-label">JD records</p><p className="mt-3 text-3xl font-semibold text-[#00B5E2]">{jds.length}</p></div><div className="hcl-card p-5"><p className="hcl-label">Pending assessments</p><p className="mt-3 text-3xl font-semibold text-[#F59E0B]">{admin.pending_assessments}</p></div><div className="hcl-card p-5"><p className="hcl-label">Teams composed</p><p className="mt-3 text-3xl font-semibold text-[#00D4AA]">{admin.teams_composed}</p></div></section><section className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><form onSubmit={submit} className="hcl-card h-fit space-y-4 p-6"><div><p className="hcl-label">New opportunity</p><h2 className="mt-2 text-xl font-semibold">Analyse a JD</h2></div><input value={clientName} onChange={(event) => setClientName(event.target.value)} placeholder="Client name" className="hcl-input w-full" required /><textarea value={rawText} onChange={(event) => setRawText(event.target.value)} placeholder="Paste the job description here..." className="hcl-input min-h-48 w-full" required /><button className="hcl-button-primary w-full">Run JD Agent</button>{message ? <p className="text-sm text-[#00D4AA]">{message}</p> : null}{error ? <p className="text-sm text-[#EF4444]">{error}</p> : null}</form><div className="hcl-table"><div className="flex items-center justify-between border-b border-[#1E2D45] bg-[#1A2235] p-5"><h2 className="text-lg font-semibold">Opportunity records</h2><span className="text-xs text-[#8899BB]">{jds.length} records</span></div><div className="divide-y divide-[#1E2D45]">{jds.length ? jds.map((jd) => <div key={jd.id} className="p-5 hover:bg-[#1A2235]"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="text-xs text-[#8899BB]">{jd.client_name} · JD #{jd.id}</p><h3 className="mt-1 font-semibold">{jd.raw_text.slice(0, 110)}{jd.raw_text.length > 110 ? "..." : ""}</h3><span className={`mt-3 inline-block rounded-full px-2 py-1 text-xs uppercase ${jd.is_published ? "bg-[#00D4AA]/10 text-[#00D4AA]" : "bg-[#F59E0B]/10 text-[#F59E0B]"}`}>{jd.status}</span></div><div className="flex flex-wrap gap-2"><Link href={`/admin/jds/${jd.id}/matches`} className="hcl-button-secondary text-sm">Matches</Link><button onClick={() => void changeStatus(jd)} className="hcl-button-primary text-sm">{jd.is_published ? "Close" : "Publish"}</button></div></div></div>) : <p className="p-6 text-sm text-[#8899BB]">No JDs available.</p>}</div></div></section></div>;
}
