"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useSearchParams, useRouter } from "next/navigation";
import ArenaChat from "@/components/ArenaChat";
import { apiFetch, hasRole } from "@/lib/api";
import type { Assessment, AssessmentResult, NextQuestion } from "@/types/api";

type Message = { role: "assistant" | "user"; text: string };

export default function AssessmentPage() {
  const params = useParams<{ id: string }>();
  const searchParams = useSearchParams();
  const router = useRouter();
  const [assessmentId, setAssessmentId] = useState<number | null>(params.id === "new" ? null : Number(params.id));
  const [assessment, setAssessment] = useState<Assessment | null>(null);
  const [result, setResult] = useState<AssessmentResult | null>(null);
  const [answer, setAnswer] = useState("");
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function loadAssessment(id: number) { const current = await apiFetch<Assessment>(`/assessments/${id}`); setAssessment(current); if (current.status === "completed") setResult(await apiFetch<AssessmentResult>(`/assessments/${id}/result`)); }
  useEffect(() => {
    if (!hasRole("engineer")) { setError("Engineer access is required."); setLoading(false); return; }
    const start = async () => { try { let id = assessmentId; if (!id) { const jdId = Number(searchParams.get("jd_id")); if (!jdId) throw new Error("A JD is required to start an assessment."); const created = await apiFetch<Assessment>("/assessments/", { method: "POST", body: JSON.stringify({ jd_id: jdId }) }); id = created.id; setAssessmentId(id); router.replace(`/engineer/assessment/${id}`); } const current = await apiFetch<Assessment>(`/assessments/${id}`); if (current.status === "pending") await apiFetch<Assessment>(`/assessments/${id}/start`, { method: "POST" }); await loadAssessment(id); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to load assessment."); } finally { setLoading(false); } };
    void start();
  }, [assessmentId, router, searchParams]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!assessmentId || !answer.trim()) return; setSubmitting(true); setError(null); try { const next = await apiFetch<NextQuestion>(`/assessments/${assessmentId}/turn`, { method: "POST", body: JSON.stringify({ answer }) }); setAnswer(""); await loadAssessment(assessmentId); if (next.is_final) setResult(await apiFetch<AssessmentResult>(`/assessments/${assessmentId}/result`)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to submit answer."); } finally { setSubmitting(false); } }
  if (loading) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-400">Loading assessment...</main>;
  if (error || !assessment) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><p className="text-rose-300">{error ?? "Assessment unavailable."}</p><Link href="/engineer/passport" className="mt-4 inline-block text-sky-300">Back to passport</Link></main>;
  const messages: Message[] = assessment.turns.flatMap((turn) => [{ role: "assistant" as const, text: turn.question }, ...(turn.answer ? [{ role: "user" as const, text: turn.answer }] : [])]);
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><div className="mx-auto max-w-4xl"><Link href="/engineer/passport" className="text-sm text-sky-300">← Capability passport</Link><div className="mt-8 border-b border-slate-800 pb-6"><p className="text-xs uppercase tracking-[0.3em] text-violet-300">Arena assessment</p><h1 className="mt-2 text-4xl font-bold text-white">Adaptive technical interview</h1><p className="mt-3 text-slate-400">Questions and evaluations are generated by the Arena Agent.</p></div><div className="mt-8"><ArenaChat messages={messages} /></div>{result ? <section className="mt-6 rounded-3xl border border-emerald-500/30 bg-emerald-500/10 p-6"><p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Assessment complete</p><h2 className="mt-2 text-2xl font-semibold text-white">{result.readiness_level}</h2><p className="mt-2 text-slate-300">{result.summary}</p><div className="mt-5 flex flex-wrap gap-2">{result.scores.map((score) => <span key={score.skill_id} className="rounded-full border border-emerald-300/30 px-3 py-1 text-xs text-emerald-100">{score.skill_name}: {score.score}/10</span>)}</div></section> : <form onSubmit={submit} className="mt-6 rounded-3xl border border-slate-800 bg-slate-900/80 p-5"><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} className="h-36 w-full resize-none rounded-2xl border border-slate-700 bg-slate-950 p-4 text-slate-200 outline-none focus:border-sky-500" placeholder="Write your answer..." required /><button disabled={submitting} className="mt-4 rounded-full bg-sky-500 px-5 py-3 text-sm text-slate-950 disabled:opacity-60">{submitting ? "Evaluating..." : "Submit answer"}</button></form>}{error ? <p className="mt-4 text-sm text-rose-300">{error}</p> : null}</div></main>;
}
