"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch, hasRole } from "@/lib/api";
import type { AdminAssessment, AdminDashboard, Application } from "@/types/api";

export default function AdminDashboardPage() {
  const [data, setData] = useState<AdminDashboard | null>(null); const [applications, setApplications] = useState<Application[]>([]); const [assessments, setAssessments] = useState<AdminAssessment[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!hasRole("admin", "leadership")) { setError("Admin or leadership access is required."); return; } Promise.all([apiFetch<AdminDashboard>("/dashboard/admin"), apiFetch<Application[]>("/admin/applications"), apiFetch<AdminAssessment[]>("/dashboard/admin/assessments")]).then(([dashboard, apps, assessmentRows]) => { setData(dashboard); setApplications(apps); setAssessments(assessmentRows); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load admin dashboard.")); }, []);
  if (error) return <main className="text-[#F0F4FF]"><p className="text-[#EF4444]">{error}</p><Link href="/login" className="mt-4 inline-block text-[#00B5E2]">Sign in</Link></main>;
  if (!data) return <main className="text-[#8899BB]">Loading admin dashboard...</main>;
  return <div><header className="mb-8"><p className="hcl-label">Admin portal</p><h1 className="mt-2 text-2xl font-semibold">Delivery pipeline</h1><p className="mt-2 text-[#8899BB]">Monitor opportunities, applications, and assessment flow.</p></header><section className="mb-8 grid gap-4 md:grid-cols-4">{[["Open JDs", data.open_jds], ["Applications", applications.length], ["Pending assessments", data.pending_assessments], ["Teams composed", data.teams_composed]].map(([label, value]) => <div key={String(label)} className="hcl-card p-5"><p className="hcl-label">{label}</p><p className="mt-3 text-3xl font-semibold text-[#00B5E2]">{value}</p></div>)}</section><section className="grid gap-6 lg:grid-cols-2"><div className="hcl-card p-6"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">Recent matches</h2><Link href="/admin/jds" className="text-sm text-[#00B5E2]">JDs</Link></div>{data.recent_matches.length ? <div className="space-y-3">{data.recent_matches.map((match, index) => <div key={`${match.engineer}-${index}`} className="flex justify-between border-b border-[#1E2D45] pb-3 text-sm"><span>{match.engineer} · {match.jd}</span><span className="text-[#00D4AA]">{match.score}%</span></div>)}</div> : <p className="text-sm text-[#8899BB]">No matches recorded.</p>}</div><div className="hcl-card p-6"><div className="mb-4 flex justify-between"><h2 className="text-lg font-semibold">Assessment activity</h2><Link href="/admin/assessments" className="text-sm text-[#00B5E2]">View all</Link></div>{assessments.length ? <div className="space-y-3">{assessments.slice(0, 5).map((assessment) => <div key={assessment.id} className="flex justify-between border-b border-[#1E2D45] pb-3 text-sm"><span>{assessment.engineer_name} · {assessment.client_name}</span><span className="text-[#8899BB]">{assessment.status}</span></div>)}</div> : <p className="text-sm text-[#8899BB]">No assessments recorded.</p>}</div></section></div>;
}
