"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { apiFetch, hasRole } from "@/lib/api";

type JD = { id: number; client_name: string };
type Team = { jd_id: number; composition: Array<{ engineer_id: number; engineer_name: string; role: string; rationale: string; capability_score: number }>; team_capability_score: number; engagement_capability_score: number; risk_level: string; swap_explanations: string[] };

export default function TeamComposePage() {
  const [jds, setJds] = useState<JD[]>([]);
  const [jdId, setJdId] = useState("");
  const [size, setSize] = useState(6);
  const [team, setTeam] = useState<Team | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!hasRole("admin", "leadership")) { setError("Admin or leadership access is required."); return; } apiFetch<JD[]>("/jds/").then((items) => { setJds(items); if (items[0]) setJdId(String(items[0].id)); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load JDs")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); try { setTeam(await apiFetch<Team>("/teams/compose", { method: "POST", body: JSON.stringify({ jd_id: Number(jdId), size }) })); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to compose team"); } }
  if (error && !jds.length) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><p className="text-rose-300">{error}</p><Link href="/login" className="mt-4 inline-block text-sky-300">Sign in</Link></main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><div className="mx-auto max-w-5xl"><Link href="/admin/jds" className="text-sm text-sky-300 hover:text-white">← Admin opportunities</Link><div className="mt-8 border-b border-slate-800 pb-6"><p className="text-xs uppercase tracking-[0.3em] text-emerald-300">Team composer</p><h1 className="mt-2 text-4xl font-bold text-white">Build a delivery team</h1><p className="mt-3 text-slate-400">The orchestrator will select from engineers and matches stored in the database.</p></div><form onSubmit={submit} className="mt-8 flex flex-col gap-4 rounded-3xl border border-slate-800 bg-slate-900/80 p-6 sm:flex-row sm:items-end"><label className="flex-1 text-sm text-slate-300">Opportunity<select value={jdId} onChange={(event) => setJdId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" required>{jds.map((jd) => <option key={jd.id} value={jd.id}>{jd.client_name} (#{jd.id})</option>)}</select></label><label className="text-sm text-slate-300">Team size<input value={size} onChange={(event) => setSize(Number(event.target.value))} type="number" min={1} max={20} className="mt-2 w-28 rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label><button className="rounded-full bg-emerald-500 px-5 py-3 text-sm font-medium text-slate-950">Compose team</button></form>{error ? <p className="mt-4 text-sm text-rose-300">{error}</p> : null}{team ? <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Team capability</p><p className="mt-2 text-3xl font-semibold text-emerald-400">{Math.round(team.team_capability_score)}%</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Engagement fit</p><p className="mt-2 text-3xl font-semibold text-white">{Math.round(team.engagement_capability_score)}%</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Risk</p><p className="mt-2 text-3xl font-semibold text-amber-300">{team.risk_level}</p></div></div><div className="mt-8 space-y-3">{team.composition.map((member) => <article key={member.engineer_id} className="rounded-2xl border border-slate-800 p-4"><div className="flex items-center justify-between"><div><h2 className="font-medium text-white">{member.engineer_name}</h2><p className="text-sm text-slate-400">{member.role}</p></div><span className="text-emerald-300">{Math.round(member.capability_score)}%</span></div><p className="mt-2 text-sm text-slate-300">{member.rationale}</p></article>)}</div></section> : null}</div></main>;
}
