"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch, hasRole } from "@/lib/api";
import type { Application } from "@/types/api";

export default function AdminApplicationsPage() {
  const [applications, setApplications] = useState<Application[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function load() { setApplications(await apiFetch<Application[]>("/admin/applications")); }
  useEffect(() => { if (!hasRole("admin", "leadership")) { setError("Admin or leadership access is required."); return; } load().catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load applications.")); }, []);
  async function update(id: number, status: string) { try { await apiFetch(`/admin/applications/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to update application."); } }
  async function requestAssessment(id: number) { try { await apiFetch(`/admin/applications/${id}/assessment`, { method: "POST" }); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to request assessment."); } }
  if (error && !applications) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><p className="text-rose-300">{error}</p><Link href="/login" className="mt-4 inline-block text-sky-300">Sign in</Link></main>;
  if (!applications) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-400">Loading applications...</main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><div className="mx-auto max-w-6xl"><Link href="/admin/jds" className="text-sm text-sky-300">← Admin workspace</Link><div className="mt-8 border-b border-slate-800 pb-6"><p className="text-xs uppercase tracking-[0.3em] text-emerald-300">Admin workspace</p><h1 className="mt-2 text-4xl font-bold text-white">Applications</h1><p className="mt-3 text-slate-400">Review applicants and request JD-specific assessments.</p></div>{error ? <p className="mt-5 text-rose-300">{error}</p> : null}<section className="mt-8 space-y-3">{applications.length ? applications.map((application) => <article key={application.id} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm text-slate-400">{application.client_name} · JD #{application.jd_id}</p><h2 className="mt-1 text-xl font-semibold text-white">{application.engineer_name}</h2><p className="mt-2 text-sm text-slate-400">Applied {application.applied_at.slice(0, 10)}{application.match_score_snapshot != null ? ` · Match ${Math.round(application.match_score_snapshot)}%` : ""}</p></div><span className="rounded-full bg-sky-500/15 px-3 py-1 text-xs uppercase text-sky-200">{application.status.replaceAll("_", " ")}</span></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => void update(application.id, "shortlisted")} className="rounded-full border border-emerald-400/30 px-3 py-2 text-xs text-emerald-200">Shortlist</button><button onClick={() => void requestAssessment(application.id)} className="rounded-full bg-sky-500 px-3 py-2 text-xs text-slate-950">Request assessment</button><button onClick={() => void update(application.id, "selected")} className="rounded-full border border-violet-400/30 px-3 py-2 text-xs text-violet-200">Select</button><button onClick={() => void update(application.id, "rejected")} className="rounded-full border border-rose-400/30 px-3 py-2 text-xs text-rose-200">Reject</button></div></article>) : <div className="rounded-3xl border border-slate-800 p-6 text-slate-400">No applications received yet.</div>}</section></div></main>;
}
