"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { applyToOpportunity, getOpportunities, hasRole } from "@/lib/api";
import type { Opportunity } from "@/types/api";

export default function OpportunitiesPage() {
  const [opportunities, setOpportunities] = useState<Opportunity[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState<number | null>(null);
  async function load() { setOpportunities(await getOpportunities()); }
  useEffect(() => { if (!hasRole("engineer")) { setError("Engineer access is required."); return; } load().catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load opportunities.")); }, []);
  async function apply(jdId: number) { setWorking(jdId); setError(null); try { await applyToOpportunity(jdId); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to apply."); } finally { setWorking(null); } }
  if (error && !opportunities) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><p className="text-rose-300">{error}</p><Link href="/login" className="mt-4 inline-block text-sky-300">Sign in</Link></main>;
  if (!opportunities) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-400">Loading opportunities...</main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><Link href="/engineer/passport" className="text-sm text-sky-300">← Capability passport</Link><Link href="/engineer/applications" className="rounded-full border border-slate-700 px-4 py-2 text-sm">My applications</Link></div><div className="mt-8 border-b border-slate-800 pb-6"><p className="text-xs uppercase tracking-[0.3em] text-violet-300">Opportunity marketplace</p><h1 className="mt-2 text-4xl font-bold text-white">Published opportunities</h1><p className="mt-3 text-slate-400">Only opportunities published by the admin workspace appear here.</p></div>{error ? <p className="mt-5 rounded-2xl bg-rose-500/10 p-4 text-sm text-rose-200">{error}</p> : null}<section className="mt-8 grid gap-4">{opportunities.length ? opportunities.map((opportunity) => { const blueprint = opportunity.capability_blueprint as { categories?: Record<string, Array<{ skill?: string }>> } | null; const skills = Object.values(blueprint?.categories ?? {}).flat().map((item) => item.skill).filter(Boolean).slice(0, 8); return <article key={opportunity.id} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><div className="flex flex-col justify-between gap-5 md:flex-row"><div className="max-w-3xl"><p className="text-sm text-slate-400">{opportunity.client_name}</p><h2 className="mt-1 text-2xl font-semibold text-white">Opportunity #{opportunity.id}</h2><p className="mt-3 line-clamp-3 text-sm text-slate-300">{opportunity.raw_text}</p><div className="mt-4 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill} className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-200">{skill}</span>)}</div></div><div className="flex shrink-0 flex-col items-start gap-3 md:items-end"><span className="text-sm text-slate-400">{opportunity.match_score != null ? `Match ${Math.round(opportunity.match_score)}%` : "Match pending"}</span>{opportunity.application_status ? <span className="rounded-full bg-emerald-500/15 px-3 py-1 text-xs uppercase text-emerald-200">{opportunity.application_status.replaceAll("_", " ")}</span> : <button disabled={working === opportunity.id} onClick={() => void apply(opportunity.id)} className="rounded-full bg-sky-500 px-5 py-2 text-sm text-slate-950 disabled:opacity-60">{working === opportunity.id ? "Applying..." : "Apply"}</button>}<Link href={`/engineer/assessment/new?jd_id=${opportunity.id}`} className="text-xs text-slate-400 hover:text-white">Assessment is available after request</Link></div></div></article>; }) : <div className="rounded-3xl border border-slate-800 p-6 text-slate-400">No opportunities are currently available.</div>}</section></div></main>;
}
