"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import CapabilityBar from "@/components/CapabilityBar";
import ReadinessGauge from "@/components/ReadinessGauge";
import { apiFetch, getMyApplications, hasRole } from "@/lib/api";
import type { Application, EngineerDashboard } from "@/types/api";

export default function EngineerDashboardPage() {
  const [data, setData] = useState<EngineerDashboard | null>(null);
  const [applications, setApplications] = useState<Application[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!hasRole("engineer")) { setError("Engineer access is required."); return; } Promise.all([apiFetch<EngineerDashboard>("/dashboard/engineer"), getMyApplications()]).then(([dashboard, apps]) => { setData(dashboard); setApplications(apps); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load engineer dashboard.")); }, []);
  if (error) return <main className="text-[#F0F4FF]"><p className="text-[#EF4444]">{error}</p><Link href="/login" className="mt-4 inline-block text-[#00B5E2]">Sign in</Link></main>;
  if (!data) return <main className="text-[#8899BB]">Loading engineer dashboard...</main>;
  return <div><header className="mb-8 flex items-start justify-between"><div><p className="hcl-label">Engineer portal</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Capability command center</h1><p className="mt-2 text-[#8899BB]">Your current evidence, opportunities, and readiness signals.</p></div><Link href="/engineer/profile" className="hcl-button-secondary">Edit profile</Link></header><section className="mb-8 grid gap-4 sm:grid-cols-3"><div className="hcl-card p-5"><p className="hcl-label">Overall confidence</p><p className="mt-3 text-3xl font-semibold text-[#00B5E2]">{Math.round(data.overall_capability_score * 10)}%</p></div><div className="hcl-card p-5"><p className="hcl-label">Active gaps</p><p className="mt-3 text-3xl font-semibold text-[#F59E0B]">{data.active_gaps}</p></div><div className="hcl-card p-5"><p className="hcl-label">Applications</p><p className="mt-3 text-3xl font-semibold text-[#F0F4FF]">{applications.length}</p></div></section><section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><ReadinessGauge score={Math.round(data.overall_capability_score * 10)} label="Capability confidence" /><div className="hcl-card p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Recommended opportunities</h2><Link href="/engineer/opportunities" className="text-sm text-[#00B5E2]">View all</Link></div>{data.matched_opportunities.length ? <div className="space-y-4">{data.matched_opportunities.slice(0, 3).map((item) => <div key={item.jd_id}><div className="flex justify-between text-sm"><span>{item.client}</span><span className="text-[#00D4AA]">{Math.round(item.match_score)}%</span></div><CapabilityBar label="JD match" value={Math.round(item.match_score)} subtitle={item.explanation ?? "Match explanation unavailable."} tone="sky" /></div>)}</div> : <p className="text-sm text-[#8899BB]">No matched opportunities yet.</p>}</div></section><section className="mt-6 hcl-card p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Active applications</h2><Link href="/engineer/applications" className="text-sm text-[#00B5E2]">Open applications</Link></div>{applications.length ? <div className="grid gap-3 md:grid-cols-2">{applications.slice(0, 4).map((application) => <div key={application.id} className="rounded-lg border border-[#1E2D45] bg-[#1A2235] p-4"><p className="font-medium">{application.client_name ?? `JD #${application.jd_id}`}</p><span className="mt-2 inline-block rounded-full bg-[#00B5E2]/10 px-2 py-1 text-xs uppercase text-[#00B5E2]">{application.status.replaceAll("_", " ")}</span></div>)}</div> : <p className="text-sm text-[#8899BB]">You haven&apos;t applied to any opportunities yet.</p>}</section></div>;
}
