"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { apiFetch, hasRole } from "@/lib/api";

type JD = { id: number; client_name: string };
type Result = { jd_id: number; current_coverage_pct: number; projected_coverage_pct: number; gap_skills: Array<{ skill_name: string; severity: string }>; upskilling_recommendation: string; readiness_date?: string };

export default function WhatIfPage() {
  const [jds, setJds] = useState<JD[]>([]); const [jdId, setJdId] = useState(""); const [teamSize, setTeamSize] = useState(6); const [weeks, setWeeks] = useState(8); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!hasRole("admin", "leadership")) { setError("Leadership or admin access is required."); return; } apiFetch<JD[]>("/jds/").then((items) => { setJds(items); if (items[0]) setJdId(String(items[0].id)); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Unable to load JDs")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); try { setResult(await apiFetch<Result>("/teams/whatif/jd", { method: "POST", body: JSON.stringify({ jd_id: Number(jdId), team_size: teamSize, upskilling_weeks: weeks }) })); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to run scenario"); } }
  if (error && !jds.length) return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><p className="text-rose-300">{error}</p><Link href="/login" className="mt-4 inline-block text-sky-300">Sign in</Link></main>;
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-50"><div className="mx-auto max-w-5xl"><Link href="/leadership/dashboard" className="text-sm text-sky-300 hover:text-white">← Leadership dashboard</Link><div className="mt-8 border-b border-slate-800 pb-6"><p className="text-xs uppercase tracking-[0.3em] text-sky-300">Scenario planning</p><h1 className="mt-2 text-4xl font-bold text-white">What-if simulator</h1><p className="mt-3 text-slate-400">Run a real capacity projection for a stored opportunity.</p></div><form onSubmit={submit} className="mt-8 grid gap-4 rounded-3xl border border-slate-800 bg-slate-900/80 p-6 md:grid-cols-3"><label className="text-sm text-slate-300 md:col-span-3">Opportunity<select value={jdId} onChange={(event) => setJdId(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" required>{jds.map((jd) => <option key={jd.id} value={jd.id}>{jd.client_name} (#{jd.id})</option>)}</select></label><label className="text-sm text-slate-300">Team size<input value={teamSize} onChange={(event) => setTeamSize(Number(event.target.value))} type="number" min={1} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label><label className="text-sm text-slate-300">Upskilling weeks<input value={weeks} onChange={(event) => setWeeks(Number(event.target.value))} type="number" min={0} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white" /></label><button className="self-end rounded-full bg-sky-500 px-4 py-3 text-sm font-medium text-slate-950">Run scenario</button></form>{error ? <p className="mt-4 text-sm text-rose-300">{error}</p> : null}{result ? <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-900/80 p-6"><div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Current coverage</p><p className="mt-2 text-3xl font-semibold text-white">{Math.round(result.current_coverage_pct)}%</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Projected coverage</p><p className="mt-2 text-3xl font-semibold text-emerald-400">{Math.round(result.projected_coverage_pct)}%</p></div><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Readiness date</p><p className="mt-2 text-xl font-semibold text-white">{result.readiness_date?.slice(0, 10) ?? "Not projected"}</p></div></div><p className="mt-8 text-slate-300">{result.upskilling_recommendation}</p><div className="mt-5 flex flex-wrap gap-2">{result.gap_skills.map((gap) => <span key={gap.skill_name} className="rounded-full border border-amber-400/30 bg-amber-400/10 px-3 py-1 text-xs text-amber-200">{gap.skill_name} · {gap.severity}</span>)}</div></section> : null}</div></main>;
}
